### PR TITLE
Frontend backend integration

### PR DESCRIPTION
**Pull request by dcdenu4**
This PR merges in all the changes we've been making together during our co development sessions. I don't think that a very thorough review is needed. I think that we made adequate issues along the way to document what still needs to be resolved.

### CODE REVIEW

**Comment by davemfish** [comment]
Hey @dcdenu4 , thanks for opening this. I agree we don't need to review the changes, just confirm that everyone is done with their work on this branch.

I'm still seeing this 500 Error, I'm not sure if you intended that to be fixed in this branch.

```
urban-online-workflow-api-1       | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table parcel_stats has no column named job_id
urban-online-workflow-api-1       | [SQL: INSERT INTO parcel_stats (target_parcel_wkt, lulc_stats, job_id) VALUES (?, ?, ?)]
urban-online-workflow-api-1       | [parameters: ('POLYGON((-10984355.381582072 3427843.017184351, -10984158.317368524 3427842.121437926, -10984156.525875673 3427831.671062965, -10984163.094682792 3427822.1164344293, -10984275.361568086 3427695.8161884737, -10984355.680164212 3427697.3090991825, -10984355.381582072 3427843.017184351))', None, 13)]
urban-online-workflow-api-1       | (Background on this error at: https://sqlalche.me/e/14/e3q8)
urban-online-workflow-api-1       | ERROR:    Exception in ASGI application
urban-online-workflow-api-1       | Traceback (most recent call last):
urban-online-workflow-api-1       |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
urban-online-workflow-api-1       |     self.dialect.do_execute(
urban-online-workflow-api-1       |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
urban-online-workflow-api-1       |     cursor.execute(statement, parameters)
urban-online-workflow-api-1       | sqlite3.OperationalError: table parcel_stats has no column named job_id
```

**Comment by dcdenu4** [comment]
Thanks Dave. I thought I had fixed that. None the less I'm fine letting this go through and cleaning it up in its own issue / PR. I won't be able to get to this until Monday.

**Comment by phargogh** [comment]
We talked about this on the Friday coffee call and decided that we might as well just merge it and we can fix the one remaining error next week.  Thanks all!

**Comment by davemfish** [comment]
> Thanks Dave. I thought I had fixed that. None the less I'm fine letting this go through and cleaning it up in its own issue / PR. I won't be able to get to this until Monday.

My bad @dcdenu4 ! This is working for me now and I must have been missing a step in updating my environment.

**Pull request merged**
